### ISSUE TITLE
&特殊符号问题

### ISSUE THREAD

**Issue by xupeng8833** [my-dlq/blog-example#1]
当你创建job的时候，如果script里面包含一些&，<等特殊符号的时候，调用API后台会出现报错信息。

**Comment by my-dlq** [comment]
这个可以添加\\\\来进行处理，加上反斜杠的默认是当成字符串值，而不会被当成某些特殊命令。

**Comment by xupeng8833** [comment]
貌似不好使，从服务端的报错信息来看，貌似是json解析XML的时候出现的问题，感觉像是官方的api在转XML对象的时候出现问题。
![image](https://user-images.githubusercontent.com/13626864/68102233-b69ddc00-ff0c-11e9-9ec0-8f7dd20bc5fd.png)
![image](https://user-images.githubusercontent.com/13626864/68102245-c6b5bb80-ff0c-11e9-9e79-0d18844cc6bd.png)
只要是在脚本里面添加了这行处理的命令就会报错，去掉就可以正常创建Job了，sh '''sed  -i '$ s/&$//' agree/startup.sh'''
