### ISSUE TITLE
springcloud-kubernetes-feign-demo使用问题

### ISSUE THREAD

**Issue by azui007** [my-dlq/blog-example#10]
1，http://www.mydlq.club/article/31/ 文章中提到的service-rbac.yaml 没有找到。是否不需要了？
2，service-feign-interface 编译之后好像也没用到，是否不需要呢？
3，service-provider已经启动了，但是访问service-customer 还是提示fallback!。请问如何排查呢

**Comment by my-dlq** [comment]
1，service-rbac.yaml  为误写，下次更新博客时会删掉。
2，service-feign-interface 是有用的，这种抽出接口的用法只是使用 springcloud feign 的一种方式。
-  服务生产者引入接口包，实现接口中的方法；
-  服务消费者引入接口包，并且在被 @FeignClient 修饰的接口类继承该接口，这样就不用我们再手动在 feignclient 接口类中定义远程接口了。

所以，仔细看该抽出阿里的 interface 实际上是被使用的。

3，执行以下检查:
- (1) 查看 service-provider 的 kubernetes service 资源是否创建，并且里面的 port 参数为 8080。
- (2) 查看 service-provider 的 kubernetes deployment 的资源配置文件中是否定义了 containerPort。
- (3) 通过 service 的 nodePort 端口方式访问 service-provider 的接口，测试是否能够成功访问。
- (4) 检查 @FeignClient 修饰的接口类是否继承 TestInterface 接口，并且项目启动类添加了 @EnableFeignClients 注解。
- (5) 检查 service-provider 与 service-customer 是否部署在同一个命名空间。

**Comment by azui007** [comment]
> 1，service-rbac.yaml 为误写，下次更新博客时会删掉。
> 2，service-feign-interface 是有用的，这种抽出接口的用法只是使用 springcloud feign 的一种方式。
> 
> * 服务生产者引入接口包，实现接口中的方法；
> * 服务消费者引入接口包，并且在被 @FeignClient 修饰的接口类继承该接口，这样就不用我们再手动在 feignclient 接口类中定义远程接口了。
> 
> 所以，仔细看该抽出阿里的 interface 实际上是被使用的。
> 
> 3，执行以下检查:
> 
> * (1) 查看 service-provider 的 kubernetes service 资源是否创建，并且里面的 port 参数为 8080。
> * (2) 查看 service-provider 的 kubernetes deployment 的资源配置文件中是否定义了 containerPort。
> * (3) 通过 service 的 nodePort 端口方式访问 service-provider 的接口，测试是否能够成功访问。
> * (4) 检查 @FeignClient 修饰的接口类是否继承 TestInterface 接口，并且项目启动类添加了 @EnableFeignClients 注解。
> * (5) 检查 service-provider 与 service-customer 是否部署在同一个命名空间。

是我的部署方式有问题。看了博主的部署文件解决了问题。
