### ISSUE TITLE
博客相关的问题

### ISSUE THREAD

**Issue by IT-zhengang** [my-dlq/blog-example#13]
您好，我也是一名后端开发人员，看了您的博客，受益匪浅，想像您请教一下您的博客平台是如何搭建的，我也想维护一个，需要您给指导一下，谢谢！

**Comment by my-dlq** [comment]
博客是使用 Hugo 应用搭建的，需要在服务器上安装 Hugo，然后去 Hugo 官网找一个主题，运行起来后使用 MarkDown 编写文档，能够将编写的 MarkDonw 文档转换为静态页面，然后你通过 Apache 或者 Nginx 代理将静态页面代理出去即可。

具体请查看 Hugo 官网，里面有很详细的介绍 https://gohugo.io/

**Comment by IT-zhengang** [comment]
你用的是哪种主题？

**Comment by my-dlq** [comment]
模板是自己基于已有的主题改造的，与原来主题有些不同，你可以在 hugo 主题里面查找以下，应该就是前面几栏里面。
