### ISSUE TITLE
搭建prometheus的时候，一直提示“CrashLoopBackOff”

### ISSUE THREAD

**Issue by mfmwmsj** [my-dlq/blog-example#14]
你好，感谢你的博客，我在部署prometheus的过程，一直提示“CrashLoopBackoff”，细心检查了一遍，也没有发现那里配置有误。麻烦帮忙。感谢！
# kubectl get pods -o wide -n kube-system | grep prometheus
prometheus-6479c8888f-hprf8                  1/2     CrashLoopBackOff   8          18m     172.30.2.14    10.9.143.246   <none>           <none>
# kubectl logs prometheus-6479c8888f-hprf8 -n kube-system
error: a container name must be specified for pod prometheus-6479c8888f-hprf8, choose one of: [prometheus configmap-reload]
# kubectl describe pods prometheus-6479c8888f-hprf8 -n kube-system
。。。。
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned kube-system/prometheus-6479c8888f-hprf8 to 10.9.143.246
  Normal   Pulled     18m                   kubelet            Container image "jimmidyson/configmap-reload:v0.5.0" already present on machine
  Normal   Created    18m                   kubelet            Created container configmap-reload
  Normal   Started    18m                   kubelet            Started container configmap-reload
  Normal   Created    17m (x4 over 18m)     kubelet            Created container prometheus
  Normal   Started    17m (x4 over 18m)     kubelet            Started container prometheus
  Normal   Pulled     17m (x5 over 18m)     kubelet            Container image "prom/prometheus:v2.26.0" already present on machine
  Warning  BackOff    3m34s (x76 over 18m)  kubelet            Back-off restarting failed container

**Comment by mfmwmsj** [comment]
Kubernetes 部署监控工具 Prometheus，参考部署地址：http://www.mydlq.club/article/110/

**Comment by my-dlq** [comment]
请检查 Pod 中的  configmap-reload 容器的 volumeMounts 配置，是否挂载 prometheus 的 configMap 资源配置文件。

如果可以，将你的全部部署文件贴一下，看看问题所在。

**Comment by mfmwmsj** [comment]
nfs服务器部分，
root@k8smw:/nfs# cat /etc/exports 
# /etc/exports: the access control list for filesystems which may be exported
#		to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
#
#/nfs 10.9.143.0/24(rw,sync,insecure,no_root_squash,no_subtree_check)
/nfs 10.9.143.0/24(rw,sync,no_root_squash,no_subtree_check)

k8s配置NFS-Subdir-External-Provisioner：
# cat nfs-provisioner/nfs-
nfs-provisioner-deploy.yaml  nfs-storageclass.yaml        
root@k8sdb:~/blog-example/kubernetes/kubernetes-prometheus# cat nfs-provisioner/nfs-provisioner-deploy.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
spec:
  replicas: 1
  strategy: 
    type: Recreate                   ## 设置升级策略为删除再创建(默认为滚动更新)
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
      - name: nfs-client-provisioner
        #image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0
        image: registry.cn-beijing.aliyuncs.com/mydlq/nfs-subdir-external-provisioner:v4.0.0
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME     ## Provisioner的名称,以后设置的storageclass要和这个保持一致
          value: nfs-client 
        - name: NFS_SERVER           ## NFS服务器地址,需和valumes参数中配置的保持一致
          value: 10.9.143.248
        - name: NFS_PATH             ## NFS服务器数据存储目录,需和valumes参数中配置的保持一致
          value: /nfs/data
      volumes:
      - name: nfs-client-root
        nfs:
          server: 10.9.143.248       ## NFS服务器地址
          path: /nfs/data            ## NFS服务器数据存储目录
		  
# kubectl get deployment -n kube-system |grep nfs
nfs-client-provisioner      1/1     1            1           20h

# cat nfs-provisioner/nfs-storageclass.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"  ## 是否设置为默认的storageclass
provisioner: nfs-client                                   ## 动态卷分配者名称，必须和上面创建的"provisioner"变量中设置的Name一致
parameters:
  archiveOnDelete: "true"                                 ## 设置为"false"时删除PVC不会保留数据,"true"则保留数据
mountOptions: 
  - hard                                                  ## 指定为硬挂载方式
  - nfsvers=4                                             ## 指定NFS版本,这个需要根据NFSServer版本号设置 
 
 # kubectl get sc -n kube-system |grep nfs-storage
nfs-storage   nfs-client    Delete          Immediate           false                  156m

  
prometheus部分
# cat prometheus-rbac.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources: ["nodes","nodes/proxy","services","endpoints","pods"]
  verbs: ["get", "list", "watch"] 
- apiGroups: ["extensions"]
  resources: ["ingress"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-system
  
  
# cat prometheus-storage.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  capacity:          
    storage: 20Gi
  accessModes:       
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
      #- nfsvers=4
    - nfsvers=4.1
  nfs: 
    server: 10.9.143.248
    path: /nfs/prometheus
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      k8s-app: prometheus
	  
	  
# kubectl get pvc  -n kube-system
NAME         STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus   Bound    prometheus   20Gi       RWO            nfs-storage    91m
# kubectl get pv  -n kube-system
NAME         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
prometheus   20Gi       RWO            Retain           Bound    kube-system/prometheus   nfs-storage             91m
	  
	  
# cat prometheus-config.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
        cluster: "kubernetes"
        
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: prometheus


# cat prometheus-deploy.yaml 
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 30900
  selector:
    k8s-app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus
  template:
    metadata:
      labels:
        k8s-app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.26.0
        ports:
        - name: http
          containerPort: 9090
        securityContext:
          runAsUser: 65534
          privileged: true
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--web.enable-lifecycle"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention.time=10d"
        - "--web.console.libraries=/etc/prometheus/console_libraries"
        - "--web.console.templates=/etc/prometheus/consoles"
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /prometheus
          subPath: prometheus
        - name: config
          mountPath: /etc/prometheus
      - name: configmap-reload
        image: jimmidyson/configmap-reload:v0.5.0
        args:
        - "--volume-dir=/etc/config"
        - "--webhook-url=http://localhost:9090/-/reload"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: prometheus
      - name: config
        configMap:
          name: prometheus-config
		  
# kubectl get pods -n kube-system | grep prometheus
prometheus-7dc76bf79f-9jrlc                  1/2     CrashLoopBackOff   11         35m

# kubectl logs prometheus-7dc76bf79f-9jrlc -n kube-system
error: a container name must be specified for pod prometheus-7dc76bf79f-9jrlc, choose one of: [prometheus configmap-reload]

# kubectl describe pods prometheus-7dc76bf79f-9jrlc -n kube-system
Name:         prometheus-7dc76bf79f-9jrlc
Namespace:    kube-system
Priority:     0
Node:         10.9.143.246/10.9.143.246
Start Time:   Sat, 10 Jul 2021 13:47:13 +0800
Labels:       k8s-app=prometheus
              pod-template-hash=7dc76bf79f
Annotations:  <none>
Status:       Running
IP:           172.30.2.22
IPs:
  IP:           172.30.2.22
Controlled By:  ReplicaSet/prometheus-7dc76bf79f
Containers:
  prometheus:
    Container ID:  containerd://3bd914db9f0564dff0f3eff3703f550f269571d2a35af51ca7c0cfde054d23e3
    Image:         prom/prometheus:v2.26.0
    Image ID:      docker.io/prom/prometheus@sha256:38d40a760569b1c5aec4a36e8a7f11e86299e9191b9233672a5d41296d8fa74e
    Port:          9090/TCP
    Host Port:     0/TCP
    Command:
      /bin/prometheus
    Args:
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-lifecycle
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=10d
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 10 Jul 2021 14:13:45 +0800
      Finished:     Sat, 10 Jul 2021 14:13:45 +0800
    Ready:          False
    Restart Count:  10
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:        1
      memory:     512Mi
    Liveness:     http-get http://:9090/-/healthy delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:    http-get http://:9090/-/ready delay=5s timeout=10s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/prometheus from config (rw)
      /prometheus from data (rw,path="prometheus")
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-token-f4lp6 (ro)
  configmap-reload:
    Container ID:  containerd://669a345bc2e1372f6a363a2207aca89f02537347bc809f42257d506d0745f4b9
    Image:         jimmidyson/configmap-reload:v0.5.0
    Image ID:      docker.io/jimmidyson/configmap-reload@sha256:904d08e9f701d3d8178cb61651dbe8edc5d08dd5895b56bdcac9e5805ea82b52
    Port:          <none>
    Host Port:     <none>
    Args:
      --volume-dir=/etc/config
      --webhook-url=http://localhost:9090/-/reload
    State:          Running
      Started:      Sat, 10 Jul 2021 13:47:15 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:        50m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /etc/config from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-token-f4lp6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-config
    Optional:  false
  prometheus-token-f4lp6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-token-f4lp6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  27m                    default-scheduler  Successfully assigned kube-system/prometheus-7dc76bf79f-9jrlc to 10.9.143.246
  Normal   Pulled     27m                    kubelet            Container image "jimmidyson/configmap-reload:v0.5.0" already present on machine
  Normal   Created    27m                    kubelet            Created container configmap-reload
  Normal   Started    27m                    kubelet            Started container configmap-reload
  Normal   Pulled     26m (x4 over 27m)      kubelet            Container image "prom/prometheus:v2.26.0" already present on machine
  Normal   Created    26m (x4 over 27m)      kubelet            Created container prometheus
  Normal   Started    26m (x4 over 27m)      kubelet            Started container prometheus
  Warning  BackOff    2m37s (x122 over 27m)  kubelet            Back-off restarting failed container

**Comment by mfmwmsj** [comment]
你好，还是没有弄好呢，麻烦帮忙检查一下。使用的是ubuntu20.04的服务器，按你博客的思路整理的，除了nfs server的ip地址变了外，其他没有变动

**Comment by mfmwmsj** [comment]
十分感谢

**Comment by mfmwmsj** [comment]
执行kubectl describe pods prometheus-7dc76bf79f-9jrlc -n kube-system，最后的提示的错误是prometheus创建失败：prometheus:
    Container ID:  containerd://3bd914db9f0564dff0f3eff3703f550f269571d2a35af51ca7c0cfde054d23e3
    Image:         prom/prometheus:v2.26.0
    Image ID:      docker.io/prom/prometheus@sha256:38d40a760569b1c5aec4a36e8a7f11e86299e9191b9233672a5d41296d8fa74e
    Port:          9090/TCP
    Host Port:     0/TCP
    Command:
      /bin/prometheus
    Args:
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-lifecycle
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=10d
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 10 Jul 2021 14:13:45 +0800
      Finished:     Sat, 10 Jul 2021 14:13:45 +0800
    Ready:          False

**Comment by my-dlq** [comment]
去掉 Prometheus 部署文件中的 configmap-reload 容器，然后再启动试试，查看是否是因为这个容器导致主容器无法启动。
