### ISSUE TITLE
按照这个部署文件部署treafikv2，报错

### ISSUE THREAD

**Issue by 651016236** [my-dlq/blog-example#2]
{"ingress":"traefik-dashboard-route","level":"error","msg":"Cannot create service: subset not found","namespace":"kube-system","providerName":"kubernetescrd","serviceName":"traefik","servicePort":8080,"time":"2019-12-02T05:55:35Z"}

**Comment by my-dlq** [comment]
不知道你具体的错误，不过按错误提示，显示是不能发行 kube-system 的 Namespace，还有是错误提示了 8080 端口，请检查 Service 中是否配置 8080 端口， 请严格按照所述进行配置，这个部署文件是经过测试过，没问题的。
