### ISSUE TITLE
按你的文件部署，为什么node上的80和443端口不是open状态

### ISSUE THREAD

**Issue by GounGG** [my-dlq/blog-example#4]
直接使用你的文件

**Comment by GounGG** [comment]
必须加上：hostNetwork: true
端口才会打开，是必须这样吗？还是有其他方法，感谢

**Comment by my-dlq** [comment]
请问 你指的是哪个应用的部署文件

**Comment by GounGG** [comment]
> 请问 你指的是哪个应用的部署文件

traefik,用你的2.2的yaml文件，目前我加了`hostNetwork: true`是可以正常工作的，但是我不是很明白为什么你的示例里都是不加的，方便详细解释一下么？

**Comment by my-dlq** [comment]
> > 请问你指的是哪些应用的部署文件
> 
> traefik，用你的2.2的yaml文件，目前我加了`hostNetwork: true`是可以正常工作的，但是我不是很明白为什么你的示例里都是不加的，方便详细解释一下么？

hostNetwork 是一对将 k8s 集群外流量引入的一种策略，跟 Service NodePort 一样，可以使外部流量进入 Kubernetes 中，如果指定 Pod 为 hostNetwork 会将该 Pod 与 Pod 所在节点服务器的所以端口进行关联进行监听，且只绑定域名为该节点，通过域名访问服务时会被该 Pod 监听到，然后 traefik 进行反向代理。

不过，部署脚本中，在 containers.port 中设置了 hostPort，作用也是监听所在节点服务器的 80 与 443 端口， 效果和指定hostNetwork: true 差不多，所以正常来说，不应该出现该问题，它俩作用是类似的。

不过这俩有些许不同：

- 指定 hostNetwork 为 true 时，容器将直接使用Pod节点的网络。
- 指定 hostport 时，流量先经过节点主机网络，然后转发到 ipstalbes 中，然后再转发到容器中。  

具体因为不清楚你的 k8s 和节点服务器的配置，所以给出两点建议吧：

1、检测下你的域名绑定的服务器，是否为 traefik pod 启动的节点服务器。
2、查看确保开启 iptables 依赖模块与清理下节点的 iptables 规则，然后再进行测试。
