### ISSUE TITLE
请教大神，你这个数据怎么来的

### ISSUE THREAD

**Issue by peacetrue** [my-dlq/blog-example#6]
![image](https://user-images.githubusercontent.com/38878763/93695200-d222cd00-fb46-11ea-8833-84f1ce5048ac.png)

zookeeper 的 200+ 表示不理解，官方的测试数据如下：

![image](https://user-images.githubusercontent.com/38878763/93695225-1a41ef80-fb47-11ea-8a9f-774acf76e9b9.png)

**Comment by peacetrue** [comment]
【对部分方案进行了简单测试，由于没有精细的配置组件环境和参数所以这里的数据不一定准确，只供参考】仅供参考吧

**Comment by my-dlq** [comment]
经过 4C8G 虚机启的 Zookeeper 测试，不论是删除节点还是计数器，创建 ID 的速度都差不多 800/s 以内的性能。你发的图的是 Zookeeper 的吞吐量，是每秒钟的请求速度，并不能表达出它节点的创建与删除的性能，如果是集群模式，那么zookeeper 集群会强一致性，可能速度更慢。
