### ISSUE TITLE
kubernetes-dashboard2.1.0-deploy errers with kubernetes v1.19.7

### ISSUE THREAD

**Issue by hillbun** [my-dlq/blog-example#8]
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "https:kubernetes-dashboard:",
    "kind": "services"
  },
  "code": 403
}
```

kubectl apply -f k8s-dashboard-rbac.yaml
kubectl apply -f k8s-dashboard-configmap-secret.yaml
kubectl apply -f k8s-dashboard-deploy.yaml
kubectl apply -f kubernetes-metrics-scraper.yaml
kubectl apply -f k8s-dashboard-token.yaml

I run these script.

**Comment by my-dlq** [comment]
> ```
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {
>     
>   },
>   "status": "Failure",
>   "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\"",
>   "reason": "Forbidden",
>   "details": {
>     "name": "https:kubernetes-dashboard:",
>     "kind": "services"
>   },
>   "code": 403
> }
> ```
> 
> kubectl apply -f k8s-dashboard-rbac.yaml
> kubectl apply -f k8s-dashboard-configmap-secret.yaml
> kubectl apply -f k8s-dashboard-deploy.yaml
> kubectl apply -f kubernetes-metrics-scraper.yaml
> kubectl apply -f k8s-dashboard-token.yaml
> 
> I run these script.

Obviously, the message says that System :anonymous cannot obtain permissions. Please check to see if RBAC has been successfully deployed.
