### ISSUE TITLE
trafik2.4按照 部署后出现问题

### ISSUE THREAD

**Issue by hellozhang** [my-dlq/blog-example#9]
![微信截图_20210406171104](https://user-images.githubusercontent.com/6902549/113687712-34b27380-96fb-11eb-8900-7d85322b8d80.png)
![微信截图_20210406171042](https://user-images.githubusercontent.com/6902549/113687723-35e3a080-96fb-11eb-9df0-cdb6368faf37.png)

**Comment by hellozhang** [comment]
0406 08:56:34.928134 1 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
{"ingress":"traefik-dashboard-route","level":"error","msg":"subset not found for kube-system/traefik","namespace":"kube-system","providerName":"kubernetescrd","time":"2021-04-06T08:56:34Z"}

**Comment by hellozhang** [comment]
failed to list *v1alpha1.Gateway: the server could not find the requested resource (get gateways.networking.x-k8s.io)

**Comment by hellozhang** [comment]
整体报错就是上面那2个

**Comment by hellozhang** [comment]
https://github.com/traefik/traefik/issues/6821   有类似问题

**Comment by my-dlq** [comment]
第一个错误猜测可能两种：
  1、没有部署的 RBAC 资源文件，或者部署的 RBAC 资源文件中没有配置 networking.x-k8s.io 相关权限。
  2、没有部署 Kubernetes Gateway CRD 资源，导致无法找到该资源，但是配置文件中却启用了 kubernetes gateway 资源。


第二个问题是 Ingress API版本的问题，只是一个警告 warning 级别，将 Ingress extensions/vabeta1 版本版本换成新的 Ingress networking.k8s.io/v1 就不会出现了。




在2021年4月6日 ***@***.***> 写道：

整体报错就是上面那2个

**Comment by hellozhang** [comment]
使用 CRD 方式配置 Traefik 路由规则
 Ingressroute 部署的

也需要部署一下 Kubernetes Gateway ，下面2个文件？？
kubernetes-gateway-crd.yaml
kubernetes-gatewayclass.yaml

**Comment by hellozhang** [comment]
使用 CRD 方式配置 Traefik 路由规则
 Ingressroute 部署的

也需要部署一下 Kubernetes Gateway ，下面2个文件？？
kubernetes-gateway-crd.yaml
kubernetes-gatewayclass.yaml

**Comment by my-dlq** [comment]
如果不想使用 kubernetes-gateway 功能，可以在配置中关掉它，在配置文件中找到：

  providers: kubernetesCRD:""
  kubernetesIngress:""
  kubernetesGateway:""

这三个配置分别是控制三种路由方式的开关，加上这个配置就想当与开启。
这里可以去掉 kubernetesGateway:"" 这一段配置，来关闭该功能。

且如果不想使用 Kubernetes Gateway 功能，可以不用部署 kubernetes-gateway-crd.yaml、kubernetes-gatewayclass.yaml 资源文件，都是灵活可选则。

**Comment by my-dlq** [comment]
如果不想使用  Kubernetes Gateway  功能就将配置文件中的 Kubernetes Gateway 配置去掉，自然也不需要部署


kubernetes-gateway-crd.yaml
kubernetes-gatewayclass.yaml


这两个文件。


在2021年4月6日 ***@***.***> 写道：

使用 CRD 方式配置 Traefik 路由规则
Ingressroute 部署的

也需要部署一下 Kubernetes Gateway ，下面2个文件？？
kubernetes-gateway-crd.yaml
kubernetes-gatewayclass.yaml

**Comment by hellozhang** [comment]
我执行了依次执行一下脚本

kubectl apply -f traefik-crd.yaml
kubectl apply -f traefik-rbac.yaml -n kube-system
kubectl apply -f traefik-config.yaml -n kube-system
kubectl apply -f traefik-deploy.yaml -n kube-system
kubectl apply -f traefik-dashboard-route.yaml -n kube-system

traefik svc /ingressroute 已经创建OK，POD运行都是成功的
采用CRD，配置文件微调了
providers:
      kubernetesCRD: ""
删除了 这个节点
 experimental:               
      kubernetesGateway: true   ## 允许使用 Kubernetes Gateway AP

执行 curl   traefik.mydlq.club   
curl: (7) Failed connect to traefik.mydlq.club:80; 拒绝连接

host 配置 traefik.mydlq.club    maste 的IP

**Comment by hellozhang** [comment]
暂时不清楚具体到底是什么问题

**Comment by hellozhang** [comment]
所有的资源都启动成功

**Comment by hellozhang** [comment]
k8s 集群是1.20版本

**Comment by my-dlq** [comment]
1、首先，我的集群是 1.20.2，应该不会是版本的问题。
2、正常来说去掉 kubernetes gateway 的配置 pod 就不会抛 error 日志了，
3、是否配置 hosts 中添加地址映射，不加肯定是不能够正常访问的，可以尝试先使用下面命令：

`curl -H "Host: traefik.mydlq.club" http://【traefik所在服务器的IP地址】/dashboard/#/`

如果这个能够不能正常执行，则说明确实是 hosts 域名解析还是存在问题，先试试这个命令吧。

**Comment by hellozhang** [comment]
按照你的确实OK，
我直接解析成master IP，master 会自动去找，不用关心哪个节点IP啊？
